Correct issue with GTEST_DIR not being passed properly.
Note how gcc uses /usr/include/gtest (default search path) as the -I for GTEST_DIR is not on the gcc command line:
System-wide gtest is 1.14 and requires C++14 while provided one is 1.8.1.

GTEST_DIR="$PWD/deps/googletest/googletest" ./configure --user

make[1]: Leaving directory '/data/users/tmwa/proj/tmw/classic/tmwa'
find: ‘doc-gen/’: No such file or directory
g++ -std=c++0x  -I . -I ./include -DGENERATING_DEPENDENCIES -O2 -g
-fstack-protector -fno-strict-aliasing -fvisibility=hidden
-fvisibility=hidden -MG -MM \
    -MT 'ast/item_test := ' \
    -MF obj/ast/item_test.d src/ast/item_test.cpp
In file included from /usr/include/gtest/gtest-message.h:57,
                 from /usr/include/gtest/gtest-assertion-result.h:46,
                 from /usr/include/gtest/gtest.h:64,
                 from src/ast/item_test.cpp:21:
/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++
versions less than C++14 are not supported.
  270 | #error C++ versions less than C++14 are not supported.
      |  ^~~~~
Makefile:331: obj/ast/item_test.d: No such file or directory